# Generated by Django 5.2.4 on 2025-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0004_alter_observation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='observation',
            name='observation_index',
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['species', 'location', 'date_observation'], name='observation_index'),
        ),
    ]
