# Generated by Django 5.2.4 on 2025-07-09 08:25

from django.db import migrations, models
from django.utils.text import slugify


from faunatrack.models import Project

def migrate_data(apps, schema_editor):
    for project in Project.objects.all():
        project.slug = slugify(project.title + str(project.pk)) if project.title else project.title
        project.save()

def migrate_back_data(apps, schema_editor):
    for project in Project.objects.all():
        project.slug = None
        project.save()

class Migration(migrations.Migration):



    dependencies = [
        ('faunatrack', '0006_project_slug'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrate_back_data),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
