# Generated by Django 5.2.4 on 2025-07-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0007_alter_project_slug'),
    ]

    operations = [
    ]
