volumes:
  db_django_prod:                                 # <- Rename "volume_name"
    name: db_django_prod
  static_volume:
    name: static_volume

networks:
  backend_django_prod:
    driver: bridge

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: postgres
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432" # inside docker subnetwork
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    volumes:
      - db_django_prod:/var/lib/postgresql/data
    networks:
      - backend_django_prod

  django:
    build: .
    container_name: django
    tty: True
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - "8000:8000" # j'ouvre à l'extérieur
    volumes:
      - ./pythagore:/home/backend/app
      - static_volume:/home/backend/app/staticfiles
    networks:
      - backend_django_prod

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
    ports:
      - 80:80  # http
      - 443:443 # https
    networks:
      - backend_django_prod