# Generated by Django 5.2.4 on 2025-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0002_alter_location_uuid_alter_observation_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='projet',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='observation',
            name='date_observation',
            field=models.DateTimeField(),
        ),
    ]
